-- IEP Event Orchestration SaaS - Complete Database Schema
-- Generated from TypeScript types

-- =============================================================================
-- ENUMS
-- =============================================================================

CREATE TYPE "app_role" AS ENUM (
  'host', 'organizer', 'event_planner', 'venue_owner',
  'hospitality_provider', 'manager', 'tester'
);

CREATE TYPE "budget_category" AS ENUM (
  'venue', 'catering', 'entertainment', 'decorations', 'transportation',
  'marketing', 'supplies', 'services', 'other', 'hospitality', 'misc', 'vendors'
);

CREATE TYPE "change_status" AS ENUM (
  'pending', 'approved', 'rejected', 'applied', 'cancelled'
);

CREATE TYPE "change_type" AS ENUM (
  'task_update', 'event_update', 'resource_update', 'vendor_update',
  'workflow_update', 'note', 'budget'
);

CREATE TYPE "event_status_enum" AS ENUM (
  'pending', 'in_progress', 'completed', 'cancelled', 'confirmed'
);

CREATE TYPE "permission_level" AS ENUM ('admin', 'coordinator', 'viewer');

CREATE TYPE "task_priority" AS ENUM ('low', 'medium', 'high', 'urgent');

CREATE TYPE "task_status" AS ENUM (
  'not_started', 'in_progress', 'completed', 'on_hold', 'cancelled'
);

-- =============================================================================
-- TABLES
-- =============================================================================

CREATE TABLE amenity_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  price numeric,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "Authorization" (
  created_at timestamptz DEFAULT now(),
  sign_in text NOT NULL,
  sign_out text,
  userid text
);

CREATE TABLE barcode_submissions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  book_id text NOT NULL,
  email text NOT NULL,
  event_name text NOT NULL,
  ticket_number text NOT NULL,
  notes text,
  phone text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "Bookings Directory" (
  book_id text NOT NULL PRIMARY KEY,
  barcode boolean,
  confirmation boolean,
  "QR_Code" boolean,
  registry text[],
  reservation boolean,
  rsvp boolean,
  user_id text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Bookings Profile" (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  booking_type text,
  contact_info text,
  name text,
  notes text,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE TABLE budget_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id text NOT NULL,
  created_by text NOT NULL,
  item_name text NOT NULL,
  category budget_category NOT NULL,
  archived boolean NOT NULL DEFAULT false,
  actual_cost numeric,
  budget_credit numeric,
  description text,
  estimated_cost numeric,
  original_amount numeric,
  payment_due_date timestamptz,
  payment_status text,
  status text,
  vendor_contact text,
  vendor_name text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE change_logs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  action text NOT NULL,
  changed_by text NOT NULL,
  entity_id text NOT NULL,
  entity_type text NOT NULL,
  change_description text,
  field_name text,
  new_value text,
  old_value text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE change_requests (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  status change_status NOT NULL DEFAULT 'pending',
  priority task_priority NOT NULL DEFAULT 'medium',
  change_type change_type,
  description text,
  event_id text,
  field_changes jsonb,
  rejection_reason text,
  requested_by text,
  task_id text,
  applied_at timestamptz,
  applied_by text,
  approved_at timestamptz,
  approved_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "Check Lists" (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  entity_id text NOT NULL,
  entity_type text NOT NULL,
  label text NOT NULL,
  assigned_to text,
  category text,
  checked boolean,
  completed_at timestamptz,
  due_date timestamptz,
  notes text,
  sort_order integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE check_lists (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id text NOT NULL,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  resource_id text NOT NULL,
  resource_type text NOT NULL,
  title text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE checklist_templates (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name text NOT NULL,
  label text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE cm_activity (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  action text NOT NULL,
  entity_type text NOT NULL,
  changed_by text,
  entity_id text,
  event_id text,
  metadata jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE cm_audit_events (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  type text NOT NULL,
  description text,
  event_id text,
  payload jsonb,
  user_id text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE cm_change_logs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  action text NOT NULL,
  changed_by text NOT NULL,
  entity_id text NOT NULL,
  entity_type text NOT NULL,
  change_description text,
  field_name text,
  new_value text,
  old_value text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE cm_change_requests (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  rollout_timing text NOT NULL DEFAULT 'immediate',
  change_type text,
  description text,
  device_info jsonb,
  event_id text,
  field_changed text,
  location_id text,
  new_value text,
  old_value text,
  priority_tag text,
  requested_by text,
  requested_estimate_minutes integer,
  resolved_at timestamptz,
  resolved_by text,
  status text,
  task_id text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE cm_event_members (
  event_id text NOT NULL,
  user_id text NOT NULL,
  role text NOT NULL DEFAULT 'viewer',
  PRIMARY KEY (event_id, user_id)
);

CREATE TABLE cm_locations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  address text,
  city text,
  event_id text,
  name text,
  region text,
  state text,
  zip text,
  created_at timestamptz
);

CREATE TABLE cm_resources (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  availability jsonb,
  event_id text,
  location_id text,
  name text,
  role text
);

CREATE TABLE cm_tasks (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  depends_on text,
  end_date timestamptz,
  event_id text,
  locked boolean,
  name text,
  start_date timestamptz,
  status text
);

CREATE TABLE collaborator_configurations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  collaborator_types text[] NOT NULL,
  role text NOT NULL,
  assigned_user_id text,
  created_at timestamptz,
  is_coordinator boolean,
  is_viewer boolean,
  notes text,
  permission_level_text text,
  roles text[],
  team_id text,
  updated_at timestamptz
);

CREATE TABLE "Collaborators" (
  collab_type text NOT NULL,
  booking_assign_to text,
  entertainment_assign_to text,
  external_vendor_assign_to_text text,
  hospitality_assign_to text,
  marketing_assign_to_text text,
  service_rental_buy_assign_to_text text,
  service_vendor text,
  suppliers_assign_to text,
  transportation_assign_to text,
  vendors_assign_to text,
  venue_assign_to text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Communication Hub" (
  comment text NOT NULL,
  creator text[],
  subject text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE confirmation_submissions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  book_id text NOT NULL,
  confirmation_number text NOT NULL,
  email text NOT NULL,
  name text NOT NULL,
  event_id text,
  notes text,
  phone text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "Create Event" (
  userid text NOT NULL PRIMARY KEY,
  booking_type text[],
  contact_name text,
  contact_phone_nbr integer,
  email text,
  entertainment_type text[],
  event_budget numeric,
  event_collaborators text[],
  event_description text,
  event_end_date timestamptz,
  event_end_time text,
  event_location text[],
  event_start_date timestamptz,
  event_start_time text,
  event_theme text[],
  "Hospitality_Location" integer,
  hospitality_type_arr text[],
  is_booking_available boolean,
  is_service_rental_available boolean,
  is_service_type_availabe boolean,
  is_service_vendor boolean,
  is_supply_available boolean,
  is_transportation_available boolean,
  is_venue_available boolean,
  marketing_type_arr text[],
  notification text,
  priority text[],
  resource_cost numeric,
  resources text[],
  service_rental_type text,
  supplier_type text[],
  transportation_type text,
  transportation_type_arr text[],
  "Venue_Location" text[],
  venue_type text[],
  created_at timestamptz DEFAULT now()
);
CREATE TABLE discussion_comment_likes (
  comment_id text NOT NULL,
  user_id text NOT NULL,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (comment_id, user_id)
);

CREATE TABLE discussion_comments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  content text NOT NULL,
  user_id text NOT NULL,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_edited boolean NOT NULL DEFAULT false,
  mentions text[] NOT NULL DEFAULT '{}',
  author_avatar_url text,
  author_display_name text,
  entity_id text,
  entity_title text,
  entity_type text,
  parent_id text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE email_events (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  recipient text NOT NULL,
  template text NOT NULL,
  error text,
  event_id text,
  metadata jsonb,
  provider text,
  status text NOT NULL DEFAULT 'sent',
  user_id text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Entertainment Directory" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city text,
  "DJ Music" text,
  Musicians text,
  Other text,
  Performer text,
  region text,
  Speaker text,
  Stage_Production text,
  "Standup Comic" text,
  state text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Entertainment Profile" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Available_Dates text,
  Business_Location text,
  Business_Name text,
  Contact_Name text,
  Contact_Ph_Nbr integer,
  Email text,
  Genre text,
  Price numeric,
  type_id text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE entertainment_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE entertainments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  business_name text NOT NULL,
  checklist jsonb,
  checklist_completed_count integer,
  city text,
  contact_name text,
  custom_type text,
  description text,
  email text,
  ent_type_id integer,
  entertainment_directory_id integer,
  instagram_url text,
  linkedin_url text,
  phone_number text,
  price numeric,
  rating numeric,
  state text,
  zip text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "Event Analytics" (
  event_id integer NOT NULL PRIMARY KEY,
  avg_task_duration numeric,
  event_count_update integer,
  event_freq_by_location text,
  lead_conversion_rate numeric,
  resource_util_percent numeric,
  task_completion_rate numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Event Plan Report" (
  userid text NOT NULL PRIMARY KEY,
  booking_type text,
  event_attendee_count integer,
  event_budget numeric,
  event_collaborators_name text,
  event_comments text,
  event_description text,
  event_end_date timestamptz,
  event_end_time text,
  event_entertain_biz_name text,
  event_entertain_collab_name text,
  event_entertain_contact_name text,
  event_entertain_contact_nbr integer,
  event_entertain_cost numeric,
  event_entertain_email text,
  event_entertain_end_date timestamptz,
  event_entertain_location text,
  event_entertain_start_date timestamptz,
  event_entertain_type text,
  event_ext_vendor_biz_name text,
  event_ext_vendor_collab_name text,
  event_ext_vendor_contact_name text,
  event_ext_vendor_contact_nbr integer,
  event_ext_vendor_cost numeric,
  event_ext_vendor_email text,
  event_ext_vendor_type text,
  event_hosp_biz_name text,
  event_hosp_check_in_date timestamptz,
  event_hosp_check_out_date timestamptz,
  event_hosp_contact_name text,
  event_hosp_contact_nbr integer,
  event_hosp_cost numeric,
  event_hosp_location text,
  event_hosp_type text,
  event_location text,
  event_market_biz_name text,
  event_market_collab_name text,
  event_market_contact_name text,
  event_market_contact_nbr integer,
  event_market_cost numeric,
  event_market_email text,
  event_market_type text,
  event_priority text,
  event_service_rental_buy_biz_name text,
  event_service_rental_buy_collab_name text,
  event_service_rental_buy_contact_name text,
  event_service_rental_buy_contact_nbr integer,
  event_service_rental_buy_cost budget_category,
  event_service_rental_buy_email text,
  event_service_rental_buy_end_date timestamptz,
  event_service_rental_buy_location text,
  event_service_rental_buy_start_date timestamptz,
  event_service_rental_buy_type text,
  event_service_vendor_biz_name text,
  event_service_vendor_collab_name text,
  event_service_vendor_contact_name text,
  event_service_vendor_contact_nbr integer,
  event_service_vendor_cost budget_category,
  event_service_vendor_email text,
  event_service_vendor_end_date timestamptz,
  event_service_vendor_location text,
  event_service_vendor_start_date timestamptz,
  event_service_vendor_type text,
  event_start_date timestamptz,
  event_start_time text,
  event_status text,
  event_supplier_biz_name text,
  event_supplier_collab_name text,
  event_supplier_contact_name text,
  event_supplier_contact_nbr integer,
  event_supplier_cost budget_category,
  event_supplier_email text,
  event_supplier_end_date timestamptz,
  event_supplier_location text,
  event_supplier_start_date timestamptz,
  event_supplier_type text,
  event_theme text,
  event_total_cost numeric,
  event_transport_biz_name text,
  event_transport_collab_name text,
  event_transport_contact_name text,
  event_transport_contact_nbr integer,
  event_transport_cost numeric,
  event_transport_email text,
  event_transport_end_date timestamptz,
  event_transport_location text,
  event_transport_start_date timestamptz,
  event_transport_type text,
  event_type text,
  event_vend_biz_name text,
  event_vend_collab_name text,
  event_vend_contact_name text,
  event_vend_contact_nbr integer,
  event_vend_cost budget_category,
  event_vend_email text,
  event_vend_end_date timestamptz,
  event_vend_location text,
  event_vend_start_date timestamptz,
  event_vend_type text,
  event_venue_biz_name text,
  event_venue_check_in_date timestamptz,
  event_venue_check_out_date timestamptz,
  event_venue_collab_name text,
  event_venue_contact_name text,
  event_venue_contact_nbr integer,
  event_venue_cost numeric,
  event_venue_location text,
  event_venue_type text,
  hosp_email text,
  user_contact_name text,
  user_contact_nbr integer,
  user_name text,
  venue_email text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Event Resources" (
  event_id integer PRIMARY KEY,
  booking_types_text text,
  entertainment_types_text text,
  external_vendor_types_text text,
  hospitality_types text,
  marketing_types_text text,
  service_rental_buy_type text,
  service_vendor_types text,
  supplier_types text,
  transportation_types_text text,
  vendor_types text,
  venue_types text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE event_resource_selections (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id text NOT NULL,
  resource_id text NOT NULL,
  selection_type text NOT NULL,
  notes text,
  status text NOT NULL DEFAULT 'selected',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE event_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  parent_id integer,
  theme_id integer,
  created_at timestamptz DEFAULT now()
);
CREATE TABLE events (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  start_date timestamptz NOT NULL,
  venue text NOT NULL,
  user_id text NOT NULL,
  archived boolean NOT NULL DEFAULT false,
  venue_booking_completed boolean NOT NULL DEFAULT false,
  budget numeric,
  description text,
  end_date timestamptz,
  end_time text,
  entertainment_id text,
  entertainment_ids text[],
  expected_attendees integer,
  external_supplier_ids text[],
  location text,
  organization_id text,
  service_rental_buy_id text,
  service_vendor_id text,
  service_vendor_ids text[],
  start_time text,
  status event_status_enum,
  theme_id integer,
  type_id integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "external_vendor directory" (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  category text NOT NULL,
  type text NOT NULL,
  manual_entry text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "external_vendor profile" (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  external_vendor_directory_id text,
  business_name text,
  contact_name text,
  email text,
  manual_entry text,
  notes text,
  phone text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "Hospitality Directory" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Airbnb text,
  city text,
  Hotel text,
  Motel text,
  Other text,
  region text,
  Resort text,
  state text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Hospitality Profile" (
  hosp_type_id budget_category NOT NULL,
  hosp_amendities text[],
  hosp_biz_name text,
  hosp_contact_name text,
  hosp_contact_nbr integer,
  hosp_email text,
  hosp_location text[],
  hosp_price numeric,
  hosp_website text,
  hospitality_type integer,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE hospitality_profile_amenities (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  amenity_type_id integer NOT NULL,
  hospitality_profile_id text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE hospitality_profiles (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  business_name text NOT NULL,
  checklist jsonb,
  checklist_completed_count integer,
  city text,
  contact_name text,
  cost numeric,
  email text,
  hospitality_type integer,
  instagram_url text,
  linkedin_url text,
  make_reservations text,
  phone_number text,
  rating numeric,
  state text,
  website text,
  zip text,
  capacity integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE hospitality_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE invoices (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id text NOT NULL,
  amount integer NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'usd',
  status text NOT NULL DEFAULT 'draft',
  billing_period_end timestamptz,
  billing_period_start timestamptz,
  description text,
  due_date timestamptz,
  invoice_number text,
  paid_at timestamptz,
  plan_name text,
  stripe_invoice_id text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "Manage Event" (
  event_user_id text NOT NULL,
  bookings_type text[],
  entertainment_type text[],
  event_budget_cost numeric[],
  event_contact_email text,
  event_contact_name text,
  event_contact_ph_nbr integer,
  event_date timestamptz,
  event_status event_status_enum,
  event_theme text,
  event_time text,
  event_type text,
  external_vendor_type text[],
  hosp_biz_name text,
  hosp_booking_date timestamptz,
  hosp_booking_time text,
  hosp_contact_name text,
  hosp_contact_nbr integer,
  hosp_cost numeric,
  hosp_email text,
  hosp_location text,
  marketing_type text[],
  service_rental_buy_type text[],
  service_vendor_biz_name text,
  service_vendor_cost numeric,
  service_vendor_delivery_date timestamptz,
  service_vendor_delivery_location text,
  service_vendor_delivery_time text,
  service_vendor_type text[],
  service_vendor_types text[],
  set_priority text,
  supplier_biz_name text,
  supplier_contact_name text,
  supplier_contact_nbr integer,
  supplier_cost numeric,
  supplier_delivery_date timestamptz,
  supplier_delivery_time text,
  supplier_email text,
  supplier_types text[],
  task_status text,
  transportation_type text[],
  vendor_biz_name text,
  vendor_contact_name text,
  vendor_contact_nbr integer,
  vendor_cost numeric,
  vendor_email text,
  venue_booking_date timestamptz,
  venue_booking_time text,
  venue_contact_name text,
  venue_contact_ph_nbr integer,
  venue_cost numeric,
  venue_location text,
  venue_name text,
  venue_type text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Manage Event Tasks" (
  event_theme text NOT NULL,
  analytics_update jsonb[],
  linked_event_id text,
  progress_update text,
  resource_update text,
  task_align_update jsonb[],
  task_change_update text[],
  task_completion_time_update text,
  task_modified_date timestamptz,
  task_update text[],
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Marketing Directory" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city text,
  "Digital Ads" text,
  "Email Marketing" text,
  "Event Promo" text,
  Influencer text,
  Other text,
  "PR / Press" text,
  "Print Media" text,
  region text,
  "Social Media" text,
  state text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Marketing Profile" (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  contact_info text,
  marketing_type text[],
  name text,
  notes text,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE TABLE marketing_campaigns (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  campaign_name text,
  campaign_type text,
  end_date timestamptz,
  start_date timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE marketing_conversions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  conversion_date timestamptz NOT NULL DEFAULT now(),
  auth_user_id text,
  conversion_type text,
  subscriber_id text,
  value numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE marketing_email_deliveries (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  subscriber_id text NOT NULL,
  clicked boolean NOT NULL DEFAULT false,
  opened boolean NOT NULL DEFAULT false,
  email_id text,
  sent_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE marketing_emails (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  campaign_id text,
  email_name text,
  send_day integer,
  subject_line text,
  template_key text,
  created_at timestamptz DEFAULT now()
);
CREATE TABLE marketing_profiles (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  business_name text NOT NULL,
  address text,
  budget_range_max numeric,
  budget_range_min numeric,
  campaign_types text[],
  checklist jsonb,
  checklist_completed_count integer,
  city text,
  contact_name text,
  description text,
  email text,
  facebook_url text,
  instagram_url text,
  is_active boolean,
  linkedin_url text,
  marketing_directory_id integer,
  marketing_type_id integer,
  phone_number text,
  platforms text[],
  portfolio_url text,
  price numeric,
  price_unit text,
  rating numeric,
  specialization text,
  state text,
  target_audience text,
  total_reviews integer,
  twitter_url text,
  website text,
  zip text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE marketing_subscribers (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  email text NOT NULL,
  name text,
  organization text,
  signup_source text,
  user_type text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE marketing_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE notifications (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  message text NOT NULL,
  recipient_id text NOT NULL,
  title text NOT NULL,
  type text NOT NULL,
  channel text,
  entity_id text,
  entity_type text,
  event_id text,
  is_read boolean NOT NULL DEFAULT false,
  sender_id text,
  sent_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE organization_members (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id text NOT NULL,
  user_id text NOT NULL,
  role text NOT NULL DEFAULT 'member',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE organizations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  owner_id text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE private_profiles (
  user_id text NOT NULL PRIMARY KEY,
  email text,
  pay_method text,
  phone text
);

CREATE TABLE private_residence_responses (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  email text NOT NULL,
  phone_number text NOT NULL,
  street_address text NOT NULL,
  event_id text,
  user_id text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE profiles (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id text NOT NULL,
  avatar_url text,
  bio text,
  display_name text,
  onboarding_completed_at timestamptz,
  subscription_expires_at timestamptz,
  subscription_level text,
  subscription_plan text,
  subscription_started_at timestamptz,
  subscription_status text,
  username text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public_profiles (
  user_id text NOT NULL PRIMARY KEY,
  avatar_url text,
  display_name text,
  role text
);

CREATE TABLE qrcode_submissions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  book_id text NOT NULL,
  email text NOT NULL,
  event_name text NOT NULL,
  ticket_number text NOT NULL,
  notes text,
  phone text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE registry_submissions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  book_id text NOT NULL,
  email text NOT NULL,
  name text NOT NULL,
  selected_items jsonb NOT NULL,
  total_amount numeric NOT NULL,
  message text,
  phone text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE reservation_submissions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  book_id text NOT NULL,
  email text NOT NULL,
  name text NOT NULL,
  party_size integer NOT NULL,
  phone text NOT NULL,
  preferred_date timestamptz NOT NULL,
  preferred_time text NOT NULL,
  event_id text,
  special_requests text,
  venue_id text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE resource_categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE resource_status (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE resources (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id text NOT NULL,
  category_id integer NOT NULL,
  location text NOT NULL,
  name text NOT NULL,
  allocated integer NOT NULL DEFAULT 0,
  total integer NOT NULL DEFAULT 0,
  status_id integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE role_permission_groups (
  permission_group permission_level NOT NULL,
  role app_role NOT NULL,
  created_at timestamptz,
  PRIMARY KEY (role, permission_group)
);

CREATE TABLE rsvp_submissions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  book_id text NOT NULL,
  guest_email text NOT NULL,
  guest_name text NOT NULL,
  response_type text NOT NULL,
  event_id text,
  guest_count integer,
  special_requests text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "Service Rental/Sale Directory" (
  rental_type_id text NOT NULL PRIMARY KEY,
  audio_visual_equip text,
  child_play_equip text[],
  city text,
  entertainment_options text,
  flowers_plants text,
  game_tables text,
  housewares text,
  lighting text,
  photo_both text,
  potty_johns integer,
  prod_props text,
  region text,
  state text,
  table_chairs text,
  tents text,
  transport_options text,
  venue_space_decor text[],
  created_at timestamptz DEFAULT now()
);

CREATE TABLE service_rental_buy (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  business_name text NOT NULL,
  city text,
  contact_name text,
  description text,
  email text,
  phone_number text,
  price numeric,
  state text,
  zip text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE service_rental_buy_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_rental_buy_id text,
  vendor_rental_type_id integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE service_rental_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serv_vendor_rental_id text,
  vendor_rental_type_id integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE TABLE "Service_Vendor Profile" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Business Name" text,
  Contact_Name text,
  Contact_Ph_Nbr integer,
  Email text,
  Location text,
  Price numeric,
  service_provided_listing text,
  Service_Type text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Subscription_Plans Directory" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Enterprise numeric,
  Premium numeric,
  "Premium Plus" numeric,
  "Special Promo" text,
  Standard_Plan numeric,
  Trial text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Subscription_Plans Profile" (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  features text[],
  notes text,
  plan_name text,
  plan_type text,
  price numeric,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE TABLE "Supplier Directory" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city text,
  Distributor text,
  Food_Wholesaler text,
  Merchandizer text,
  Online_Market text,
  Other text,
  other_manual_text text,
  region text,
  state text,
  Wholesaler text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Supplier Profile" (
  supplier_id text NOT NULL PRIMARY KEY,
  distributor_supplier_biz_name text,
  merchandizer_supllier_biz_name text,
  online_marketplace_supplier_biz_name text,
  supplier_contact_name text,
  supplier_contact_nbr integer,
  supplier_email text,
  supplier_location text,
  supplier_type text,
  wholesaler_supplier_biz_name text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Supplier Vendor Profile" (
  type integer NOT NULL DEFAULT 0,
  inventory_listing text,
  supp_biz_name text,
  supp_contact_name text,
  supp_contact_nbr integer,
  supp_contact_role text,
  supp_email text,
  supp_location text,
  supp_name text,
  supp_rate numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE supplier_categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE supplier_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE suppliers (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  business_name text NOT NULL,
  category_id integer,
  checklist jsonb,
  checklist_completed_count integer,
  city text,
  contact_name text,
  custom_category text,
  custom_type text,
  description text,
  email text,
  instagram_url text,
  inventory_images text,
  linkedin_url text,
  phone_number text,
  price numeric,
  rating numeric,
  state text,
  supplier_cost numeric,
  type_id integer,
  zip text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE task_assignments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  task_id text NOT NULL,
  created_by text NOT NULL,
  user_id text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE task_collaborator_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id text NOT NULL,
  user_id text NOT NULL,
  is_collaborator boolean NOT NULL DEFAULT false,
  is_viewer boolean NOT NULL DEFAULT false,
  team_admin boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE tasks (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_by text NOT NULL,
  title text NOT NULL,
  checklist jsonb NOT NULL DEFAULT '[]'::jsonb,
  priority task_priority NOT NULL DEFAULT 'medium',
  actual_hours numeric,
  archived boolean NOT NULL DEFAULT false,
  assigned_bookings_role text,
  assigned_coordinator_name text,
  assigned_entertainment_role text,
  assigned_external_vendor_role text,
  assigned_hospitality_role text,
  assigned_service_rental_role text,
  assigned_service_vendor_role text,
  assigned_supplier_vendor_role text,
  assigned_to text,
  assigned_to_display_name text,
  assigned_transportation_role text,
  assigned_venue_role text,
  assined_vendor_role text,
  category text,
  description text,
  due_date timestamptz,
  end_date timestamptz,
  end_time text,
  estimated_hours numeric,
  event_id text,
  location_id text,
  organization_id text,
  resource_assignments jsonb,
  start_date timestamptz,
  start_time text,
  status task_status,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE tasks_assignments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_by text NOT NULL,
  event_id text NOT NULL,
  event_theme text NOT NULL,
  actual_hours numeric,
  assigned_to text,
  description text,
  due_date timestamptz,
  estimated_hours numeric,
  priority task_priority NOT NULL DEFAULT 'medium',
  status task_status,
  task_name text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE tasks_dependencies (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  task_id text NOT NULL,
  depends_on_task_id text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE tasks_old (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_by text NOT NULL,
  title text NOT NULL,
  priority task_priority NOT NULL DEFAULT 'medium',
  actual_hours numeric,
  archived boolean NOT NULL DEFAULT false,
  assign_hospitality text,
  assign_transportation text,
  assigned_bookings_role text,
  assigned_coordinator_name text,
  assigned_entertainment_role text,
  assigned_external_vendor_role text,
  assigned_hospitality_role text,
  assigned_service_rental_role text,
  assigned_service_vendor_role text,
  assigned_supplier_vendor_role text,
  assigned_to text,
  assigned_to_display_name text,
  assigned_transportation_role text,
  assigned_venue_role text,
  assignment_type text,
  assined_vendor_role text,
  category text,
  change_request_id text,
  checklist jsonb,
  description text,
  due_date timestamptz,
  end_date timestamptz,
  end_time text,
  estimated_hours numeric,
  event_id text,
  resource_assignments jsonb,
  start_date timestamptz,
  start_time text,
  status task_status,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE team_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id text NOT NULL,
  user_id text NOT NULL,
  is_collaborator boolean NOT NULL DEFAULT false,
  is_viewer boolean NOT NULL DEFAULT false,
  team_admin boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE teams (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE template_tasks (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  template_id text NOT NULL,
  title text NOT NULL,
  user_id text NOT NULL,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE templates (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  user_id text NOT NULL,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE TABLE "Themes Directory" (
  baby_shower text NOT NULL,
  bridal_shower text,
  Celebration text,
  Dining text,
  event_themes_catalog jsonb,
  Festival text,
  Health_Wellness text,
  market_place text[],
  meet_up text[],
  parties text[],
  retreats text,
  reunion text,
  special_event text[],
  sporting text[],
  wedding text
);

CREATE TABLE "Themes Directory Catalog" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  premium boolean NOT NULL DEFAULT false,
  celebration_types text[],
  description text,
  dining_types text[],
  festival_types text[],
  health_wellness_types text[],
  holiday_types text[],
  personal_types text[],
  retreat_types text[],
  reunion_types text[],
  tags text[],
  wedding_types text[],
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Transportation Directory" (
  transo_rental_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bus text[],
  car_suv text,
  city text,
  limo text,
  other text,
  region text,
  state text,
  truck text,
  van text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Transportation Profile" (
  transpo_id text NOT NULL PRIMARY KEY,
  arrival_date timestamptz,
  arrival_time text,
  biz_email text,
  biz_name text,
  confirmation_nbr integer,
  dates_available text,
  days_of_operation text[],
  departure_date timestamptz,
  departure_location text,
  departure_time text,
  destination_location text,
  hours_of_operation text[],
  seating_capacity integer,
  special_accommodations text[],
  trans_amenities text,
  trans_contact_name text,
  trans_contact_nbr integer,
  trans_type text,
  transpo_cost numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE transportation_profiles (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  business_name text NOT NULL,
  amenities text[],
  amenities_notes text,
  amenity_ids integer[],
  checklist jsonb,
  checklist_completed_count integer,
  city text,
  contact_name text,
  description text,
  email text,
  has_ac boolean,
  has_entertainment_system boolean,
  has_gps_tracking boolean,
  has_luggage_storage boolean,
  has_refreshments boolean,
  has_wheelchair_access boolean,
  has_wifi boolean,
  is_child_seat_available boolean,
  is_pet_friendly boolean,
  passenger_capacity integer,
  phone_number text,
  price numeric,
  seating_capacity integer,
  state text,
  transp_type_id integer,
  transpo_images text,
  zip text,
  capacity integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE transportation_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE transportations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  business_name text NOT NULL,
  capacity integer,
  city text,
  contact_name text,
  custom_type text,
  description text,
  email text,
  phone_number text,
  price numeric,
  profile_url text,
  seating_capacity integer,
  special_accommodations text[],
  state text,
  transp_type_id integer,
  zip text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE uploads (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  file_path text NOT NULL,
  user_id text NOT NULL,
  event_id text,
  media_type text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "User Profile" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Biz_Name text,
  Pay_Method text,
  Sibscription_Upgrade_Date timestamptz,
  Subscription_End_Date timestamptz,
  Subscription_Start_Date timestamptz,
  Subscription_type text,
  Subscription_Upgrade_Type text,
  User_Category text,
  User_Contact_Name text,
  User_Contact_Ph_Nbr integer,
  User_Email text,
  user_id text,
  User_Location text,
  User_Subscription_Freq text,
  User_Type text,
  user_upload_pics text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE user_roles (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  role app_role NOT NULL,
  user_id text NOT NULL,
  event_id text,
  permission_level permission_level,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE vendor (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  business_name text NOT NULL,
  checklist jsonb,
  checklist_completed_count integer,
  city text,
  contact_name text,
  custom_type text,
  description text,
  email text,
  instagram_url text,
  linkedin_url text,
  phone_number text,
  price numeric,
  rating numeric,
  state text,
  vendor_sup_type_id integer,
  zip text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "Vendor Directory" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Bakery text,
  Beverage text,
  Brewery text,
  Caterer text,
  Chef text,
  city text,
  Florist text,
  "Food Truck" text,
  Foodies text,
  Ice_Sculpure text,
  Mobile_Pop_Up text,
  Other text,
  other_manual_text text,
  region text,
  state text,
  Videographer text,
  Winery text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Vendor Profile" (
  vendor_type_id text NOT NULL PRIMARY KEY,
  ven_avail_dates text,
  vendor_biz_name text,
  vendor_contact_name text,
  vendor_contact_nbr integer,
  vendor_email text,
  vendor_location text,
  vendor_price numeric,
  vendor_type text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE vendor_rental_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE vendor_supplier_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "Venue Directory" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Agri_Location text,
  "Agri-Farming" text,
  Business text,
  Business_Location text,
  city text,
  Hospitality text,
  Hospitality_Location text,
  Local_Govern text,
  Local_Govern_Location text,
  Market_Location text,
  Market_Place text,
  Other text,
  Other_Location text,
  Private_Club text,
  Private_Club_Location text,
  Private_Residence_Location text,
  Private_Resident text,
  Recreation text,
  Recreation_Location text,
  region text,
  Resort text,
  Resort_Location text,
  Restaurant text,
  Restaurant_Location text,
  Sporting_Facility text,
  Sporting_Facility_Location text,
  state text,
  State_Govern text,
  State_Govern_Location text,
  Warehouse text,
  Warehouse_Location text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE "Venue Profile" (
  venue_type_id text NOT NULL PRIMARY KEY,
  ven_biz_name text,
  ven_contact_name text,
  ven_contact_ph_nbr integer,
  ven_email text,
  ven_locatiom text,
  ven_price numeric,
  ven_reservation_date timestamptz,
  ven_reservation_time text,
  venue_amenities text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE venue_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE venues (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  business_name text NOT NULL,
  amenities text[] NOT NULL DEFAULT '{}',
  amenities_notes text,
  amenity_ids integer[],
  checklist jsonb,
  checklist_completed_count integer,
  city text,
  contact_name text,
  cost numeric,
  custom_type text,
  email text,
  has_accessibility boolean,
  has_av_equipment boolean,
  has_catering boolean,
  has_outdoor_space boolean,
  has_parking boolean,
  has_wifi boolean,
  instagram_url text,
  linkedin_url text,
  phone_number text,
  price numeric,
  rating numeric,
  state text,
  user_id text,
  venue_directory_id integer,
  venue_images text,
  venue_type_id integer,
  zip text,
  capacity integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE workflow_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  tags text[],
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE workflows (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id text NOT NULL,
  user_id text NOT NULL,
  bookings_id text,
  entertainment_id text,
  external_vendor_id text,
  hospitality_id text,
  serv_vendor_id text,
  service_rental_buy_id text,
  supplier_id text,
  theme_id integer,
  transportation_id text,
  vendor_id text,
  venue_id text,
  workflow_type_id integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
-- =============================================================================
-- FOREIGN KEY CONSTRAINTS
-- =============================================================================

ALTER TABLE budget_items ADD CONSTRAINT budget_items_event_id_fkey
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;

ALTER TABLE change_requests ADD CONSTRAINT change_requests_task_id_fkey
  FOREIGN KEY (task_id) REFERENCES tasks_old(id) ON DELETE SET NULL;

ALTER TABLE check_lists ADD CONSTRAINT check_lists_event_id_fkey
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;

ALTER TABLE cm_activity ADD CONSTRAINT cm_activity_event_id_fkey
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;

ALTER TABLE cm_change_requests ADD CONSTRAINT cm_change_requests_location_id_fkey
  FOREIGN KEY (location_id) REFERENCES cm_locations(id) ON DELETE SET NULL;

ALTER TABLE collaborator_configurations ADD CONSTRAINT collaborator_configurations_team_id_fkey
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;

ALTER TABLE discussion_comment_likes ADD CONSTRAINT discussion_comment_likes_comment_id_fkey
  FOREIGN KEY (comment_id) REFERENCES discussion_comments(id) ON DELETE CASCADE;

ALTER TABLE discussion_comments ADD CONSTRAINT discussion_comments_parent_id_fkey
  FOREIGN KEY (parent_id) REFERENCES discussion_comments(id) ON DELETE SET NULL;

ALTER TABLE email_events ADD CONSTRAINT email_events_event_id_fkey
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL;

ALTER TABLE entertainments ADD CONSTRAINT entertainments_directory_id_fkey
  FOREIGN KEY (entertainment_directory_id) REFERENCES "Entertainment Directory"(id) ON DELETE SET NULL;

ALTER TABLE entertainments ADD CONSTRAINT entertainments_ent_type_id_fkey
  FOREIGN KEY (ent_type_id) REFERENCES entertainment_types(id) ON DELETE SET NULL;

ALTER TABLE event_resource_selections ADD CONSTRAINT event_resource_selections_event_id_fkey
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;

ALTER TABLE events ADD CONSTRAINT events_entertainment_id_fkey
  FOREIGN KEY (entertainment_id) REFERENCES entertainments(id) ON DELETE SET NULL;

ALTER TABLE events ADD CONSTRAINT events_organization_id_fkey
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL;

ALTER TABLE events ADD CONSTRAINT events_serv_vendor_rental_id_fkey
  FOREIGN KEY (service_rental_buy_id) REFERENCES service_rental_buy(id) ON DELETE SET NULL;

ALTER TABLE events ADD CONSTRAINT events_service_vendor_id_fkey
  FOREIGN KEY (service_vendor_id) REFERENCES vendor(id) ON DELETE SET NULL;

ALTER TABLE events ADD CONSTRAINT events_type_id_fkey
  FOREIGN KEY (type_id) REFERENCES event_types(id) ON DELETE SET NULL;

ALTER TABLE "external_vendor profile" ADD CONSTRAINT external_vendor_profile_directory_id_fkey
  FOREIGN KEY (external_vendor_directory_id) REFERENCES "external_vendor directory"(id) ON DELETE SET NULL;

ALTER TABLE "Hospitality Profile" ADD CONSTRAINT hospitality_profile_hospitality_type_fkey
  FOREIGN KEY (hospitality_type) REFERENCES hospitality_types(id) ON DELETE SET NULL;

ALTER TABLE hospitality_profile_amenities ADD CONSTRAINT hospitality_profile_amenities_amenity_type_id_fkey
  FOREIGN KEY (amenity_type_id) REFERENCES amenity_types(id) ON DELETE CASCADE;

ALTER TABLE hospitality_profile_amenities ADD CONSTRAINT hospitality_profile_amenities_hospitality_profile_id_fkey
  FOREIGN KEY (hospitality_profile_id) REFERENCES hospitality_profiles(id) ON DELETE CASCADE;

ALTER TABLE hospitality_profiles ADD CONSTRAINT hospitality_profiles_hospitality_type_fkey
  FOREIGN KEY (hospitality_type) REFERENCES hospitality_types(id) ON DELETE SET NULL;

ALTER TABLE marketing_conversions ADD CONSTRAINT marketing_conversions_subscriber_id_fkey
  FOREIGN KEY (subscriber_id) REFERENCES marketing_subscribers(id) ON DELETE SET NULL;

ALTER TABLE marketing_email_deliveries ADD CONSTRAINT marketing_email_deliveries_email_id_fkey
  FOREIGN KEY (email_id) REFERENCES marketing_emails(id) ON DELETE SET NULL;

ALTER TABLE marketing_email_deliveries ADD CONSTRAINT marketing_email_deliveries_subscriber_id_fkey
  FOREIGN KEY (subscriber_id) REFERENCES marketing_subscribers(id) ON DELETE CASCADE;

ALTER TABLE marketing_emails ADD CONSTRAINT marketing_emails_campaign_id_fkey
  FOREIGN KEY (campaign_id) REFERENCES marketing_campaigns(id) ON DELETE SET NULL;

ALTER TABLE marketing_profiles ADD CONSTRAINT marketing_profiles_marketing_directory_id_fkey
  FOREIGN KEY (marketing_directory_id) REFERENCES "Marketing Directory"(id) ON DELETE SET NULL;

ALTER TABLE marketing_profiles ADD CONSTRAINT marketing_profiles_marketing_type_id_fkey
  FOREIGN KEY (marketing_type_id) REFERENCES marketing_types(id) ON DELETE SET NULL;

ALTER TABLE notifications ADD CONSTRAINT notifications_event_id_fkey
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL;

ALTER TABLE organization_members ADD CONSTRAINT organization_members_organization_id_fkey
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;

ALTER TABLE resources ADD CONSTRAINT resources_category_id_fkey
  FOREIGN KEY (category_id) REFERENCES resource_categories(id) ON DELETE RESTRICT;

ALTER TABLE resources ADD CONSTRAINT resources_event_id_fkey
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;

ALTER TABLE resources ADD CONSTRAINT resources_status_id_fkey
  FOREIGN KEY (status_id) REFERENCES resource_status(id) ON DELETE SET NULL;

ALTER TABLE reservation_submissions ADD CONSTRAINT reservation_submissions_venue_profile_id_fkey
  FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE SET NULL;

ALTER TABLE service_rental_buy_assignments ADD CONSTRAINT serv_vendor_rental_types_serv_vendor_rental_id_fkey
  FOREIGN KEY (service_rental_buy_id) REFERENCES service_rental_buy(id) ON DELETE SET NULL;

ALTER TABLE service_rental_buy_assignments ADD CONSTRAINT serv_vendor_rental_types_vendor_rental_type_id_fkey
  FOREIGN KEY (vendor_rental_type_id) REFERENCES vendor_rental_types(id) ON DELETE SET NULL;

ALTER TABLE service_rental_types ADD CONSTRAINT service_rental_types_serv_vendor_rental_id_fkey1
  FOREIGN KEY (serv_vendor_rental_id) REFERENCES service_rental_buy(id) ON DELETE SET NULL;

ALTER TABLE service_rental_types ADD CONSTRAINT service_rental_types_vendor_rental_type_id_fkey1
  FOREIGN KEY (vendor_rental_type_id) REFERENCES vendor_rental_types(id) ON DELETE SET NULL;

ALTER TABLE suppliers ADD CONSTRAINT suppliers_category_id_fkey
  FOREIGN KEY (category_id) REFERENCES supplier_categories(id) ON DELETE SET NULL;

ALTER TABLE suppliers ADD CONSTRAINT suppliers_type_id_fkey
  FOREIGN KEY (type_id) REFERENCES supplier_types(id) ON DELETE SET NULL;

ALTER TABLE task_assignments ADD CONSTRAINT task_assignments_task_id_fkey
  FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE;

ALTER TABLE task_collaborator_assignments ADD CONSTRAINT task_collaborator_assignments_team_id_fkey
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;

ALTER TABLE tasks ADD CONSTRAINT tasks_location_id_fkey
  FOREIGN KEY (location_id) REFERENCES cm_locations(id) ON DELETE SET NULL;

ALTER TABLE tasks ADD CONSTRAINT tasks_organization_id_fkey
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL;

ALTER TABLE tasks_dependencies ADD CONSTRAINT tasks_dependencies_depends_on_task_id_fkey
  FOREIGN KEY (depends_on_task_id) REFERENCES tasks_old(id) ON DELETE CASCADE;

ALTER TABLE tasks_dependencies ADD CONSTRAINT tasks_dependencies_task_id_fkey
  FOREIGN KEY (task_id) REFERENCES tasks_old(id) ON DELETE CASCADE;

ALTER TABLE tasks_old ADD CONSTRAINT tasks_old_assign_hospitality_fkey
  FOREIGN KEY (assign_hospitality) REFERENCES hospitality_profiles(id) ON DELETE SET NULL;

ALTER TABLE tasks_old ADD CONSTRAINT tasks_old_assign_transportation_fkey
  FOREIGN KEY (assign_transportation) REFERENCES transportation_profiles(id) ON DELETE SET NULL;

ALTER TABLE tasks_old ADD CONSTRAINT tasks_old_change_request_id_fkey
  FOREIGN KEY (change_request_id) REFERENCES change_requests(id) ON DELETE SET NULL;

ALTER TABLE team_assignments ADD CONSTRAINT team_assignments_team_id_fkey1
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;

ALTER TABLE template_tasks ADD CONSTRAINT template_tasks_template_id_fkey
  FOREIGN KEY (template_id) REFERENCES templates(id) ON DELETE CASCADE;

ALTER TABLE transportation_profiles ADD CONSTRAINT transportations_transp_type_id_fkey
  FOREIGN KEY (transp_type_id) REFERENCES transportation_types(id) ON DELETE SET NULL;

ALTER TABLE transportations ADD CONSTRAINT transportations_transp_type_id_fkey1
  FOREIGN KEY (transp_type_id) REFERENCES transportation_types(id) ON DELETE SET NULL;

ALTER TABLE uploads ADD CONSTRAINT uploads_event_id_fkey
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL;

ALTER TABLE user_roles ADD CONSTRAINT user_roles_event_id_fkey
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL;

ALTER TABLE vendor ADD CONSTRAINT vendor_vendor_sup_type_id_fkey
  FOREIGN KEY (vendor_sup_type_id) REFERENCES vendor_supplier_types(id) ON DELETE SET NULL;

ALTER TABLE venues ADD CONSTRAINT venues_directory_id_fkey
  FOREIGN KEY (venue_directory_id) REFERENCES "Venue Directory"(id) ON DELETE SET NULL;

ALTER TABLE venues ADD CONSTRAINT venues_venue_type_id_fkey
  FOREIGN KEY (venue_type_id) REFERENCES venue_types(id) ON DELETE SET NULL;

ALTER TABLE workflows ADD CONSTRAINT workflows_event_id_fkey
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;

ALTER TABLE workflows ADD CONSTRAINT workflows_hospitality_id_fkey
  FOREIGN KEY (hospitality_id) REFERENCES hospitality_profiles(id) ON DELETE SET NULL;

ALTER TABLE workflows ADD CONSTRAINT workflows_serv_vendor_id_fkey
  FOREIGN KEY (serv_vendor_id) REFERENCES vendor(id) ON DELETE SET NULL;

ALTER TABLE workflows ADD CONSTRAINT workflows_serv_vendor_rent_id_fkey
  FOREIGN KEY (service_rental_buy_id) REFERENCES service_rental_buy(id) ON DELETE SET NULL;

ALTER TABLE workflows ADD CONSTRAINT workflows_supplier_id_fkey
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;

ALTER TABLE workflows ADD CONSTRAINT workflows_venue_profile_id_fkey
  FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE SET NULL;
